import { IsDateString, IsIn, IsOptional, IsString, IsUUID } from 'class-validator';

export class CreateCitaDto {
  @IsOptional()
  @IsUUID()
  usuario_id?: string;

  @IsOptional()
  @IsUUID()
  servicio_id?: string;

  @IsDateString()
  fecha!: string;

  @IsString()
  hora_inicio!: string;

  @IsString()
  hora_fin!: string;

  @IsOptional()
  @IsIn(['pendiente', 'atendida', 'cancelada'])
  estado?: 'pendiente' | 'atendida' | 'cancelada';

  // creadoEn is generated by DB
}
